### ISSUE TITLE
oneforall package

### ISSUE THREAD

**Issue by sulaimanzai** [pry0cc/axiom#151]
Hello pry0cc!

can you kindly add the https://github.com/shmilylty/OneForAll package to the axiom?

thanks in advance

**Comment by 0xtavian** [comment]
hey @sulaimanzai sorry about the wait. I've never used or even heard of OneForAll but tbh it looks bad freaking ass! If you dont wanna wait until we add it you can create your own module with the help of this new guide https://github.com/pry0cc/axiom/wiki/Adding-Simple-Modules. Unfortunately since I've never used the tool its going to take me a bit to go thru all the code and make a determination if we will add it to axiom or not. If you know of any other awesome Chinese tools please post them for sure! I say Chinese but ofc they dont have to be, I only mention Chinese because in my limited github search for Chinese offsec tools inspired by your post, I found a lot of hidden gems that I never would have heard about otherwise. Thanks again!
