### ISSUE TITLE
unix_listener: cannot bind to path No such file or directory

### ISSUE THREAD

**Issue by 0xtavian** [pry0cc/axiom#185]
fix with `mkdir $HOME/.ssh/sockets`

**Comment by honoki** [comment]
This did solve my problem, but because of [this line](https://github.com/pry0cc/axiom/blob/68d189057f3de5ad6791bf76d288a44985427d77/interact/axiom-scan#L11) it reoccurred whenever I ran `axiom-scan`.

A simple fix was to just add `mkdir $HOME/.ssh/sockets` after that line. I'm assuming the same is the case for `axiom-orgalorg` and `axiom-exec`.

**Comment by 0xtavian** [comment]
@honoki can you update to the new axiom-scan? we've removed the sockets all together.

**Comment by 0xtavian** [comment]
for anyone else seeing this error I believe running `axiom-account [your-account]` should fix it, if not then run `axiom-account-setup`

**Comment by 0xtavian** [comment]
for anyone else seeing this error, pick your provider by running `axiom-provider do` for example. If that doenst work run `axiom-account [your-account]`, if none of those work run `axiom-configure` or `axiom-account-setup`.

**Comment by chinmay90kulkarni** [comment]
It was a permission issue for me - 
@0xtavian's solution gave me pointers. Thanks for that.

**mkdir $HOME/.ssh/control  and sudo chmod 777 $HOME/.ssh/control**

above line solves my issue

**Comment by skyler544** [comment]
Commenting here because this is one of the first results on a google search about the error message in the issue title, even if the error has nothing to do with this repository.

> It was a permission issue

> chmod 777

`777` is [dangerous and unnecessary](https://askubuntu.com/a/1081080).

`sudo chmod 600 /home/yourusername/.ssh/control` fixes the issue without compromising the permissions in your `~/.ssh` directory.
