### ISSUE TITLE
some questions !

### ISSUE THREAD

**Issue by bing0o** [pry0cc/axiom#213]
hello,
thanks for this great tool, and i want to ask some question if is't possible 
1 i want to know if it's possible to create a new instance not with the default size: my default size is "s-1vcpu-1gb" and i want to create a new one with "s-2vcpu-4gb" 
2 the second one is i wanna know if i can turn an (instance or fleet) off using axiom 

thanks in advance .

**Comment by pry0cc** [comment]
You can spin up a single instance with axiom-init --size=yoursize
But you can't spin up a fleet without changing the default size just as yet. Our general guidance has been just to update the file, but we could add a size flag to the fleet command too. 

Secondly, there are no power options for axiom mainly because it doesn't have an affect on charges (last i checked I might be wrong)

**Comment by geeknik** [comment]
> Secondly, there are no power options for axiom mainly because it doesn't have an affect on charges (last i checked I might be wrong)

DO still charges for powered off resources. Unsure about other providers.

**Comment by bing0o** [comment]
@pry0cc @geeknik thank you so much guys
