### ISSUE TITLE
Feature Request: Update documentation to give more detail on creating custom images and backups

### ISSUE THREAD

**Issue by ResistanceIsUseless** [pry0cc/axiom#261]
I've been using axiom for a while but I'm still not fully grasping the format to build your own custom images. Is this using a standard format for the json files or is it custom to axiom? I have an idea for a couple custom images I want to build as my default and would like some direction on how to do that.

Also, I would also like more documentation on the backup process. If using Azure, is using a storage account possible? In general i have a lot of files in /home i would like to backup and restore across most images. This includes things like aliases and functions, etc.

**Comment by 0xtavian** [comment]
Hey @ResistanceIsUseless thanks for opening an issue about this. So as of current axiom doesnt support custom images out of the box. We are using a standard format for the image, which is packer builders https://github.com/pry0cc/axiom/tree/master/images/builders and the full.json.
https://github.com/pry0cc/axiom/blob/master/images/provisioners/full.json.

I havent used Azure in a bit but you _might_ get lucky by just changing the 'image_offer' variable in the builder to a different one.  https://github.com/pry0cc/axiom/blob/master/images/builders/azure.json#L15

Caution: the way axiom-fleet decides which image to build a fleet with is rudimentary, it simply picks the most recently built image on the account and attempts to initialize instances with that. We plan to change this in the future and store the imageid in the account.json and reference it from there, but thats a few days if not a week away.

As for documentation, we need to work on this too. backup was only intended (and only works iirc) on one box at a time. All it does is SCPs the files/folders on the remote instance home directory to the local instance. it doesnt take a snapshot of any kind so you cant provision with the files downloaded from axiom-backup, however you can restore the files with axiom-restore Admittedly I havent used either axiom-backup or axiom-restore but there are plans to make it so when running axiom-backup, it takes a snapshot of the image that you'd then beable to deploy fleets from a backup snapshot seamlessly.

a storage account is azure's S3/block-storage/etc offering right? once we fix axiom-backup to be able to save a snapshot that should work for aliases and functions, etc. I dont believe there are any plans to add file storage, mainly because its not cloud agnostic. We are more than happy to consider it, could you explain a little more about what and how youd like to use a storage account? Thanks man. Glad you are enjoying using axiom!

**Comment by ResistanceIsUseless** [comment]
I use Azure for work so i switched over from Digital Ocean. I know axiom tries to be as cost efficient as possible so adding a bunch of fancy features is low on the priority list, but I was thinking it would be nice to backup scan and config files to a single place in the cloud as opposed to locally. 

- Using fuse mount blob storage to a VM (https://github.com/Azure/azure-storage-fuse). This would be useful for continuing research without having to move files back and forth. It would also be cool to try and import scan files into elasticsearch.

- Is the purpose of the configs in profiles to be supplemental to the core image? Is that something packer supports (making changes to a VM after deployed from an image) or something axiom does manually?

I appreciate the detailed response. I do really like axiom and it's actually helped me learn a few things in azure and digital ocean. Everyone uses axiom in a pretty similar way but there is so much potential here to bring together bug bounty research and automation. I would love to be able to spin up additional custom machines or docker images for things like a collaborator server for OOB DNS testing, node-red to try and connect things together and build an automated process with an API trigger.

I'll try and help with documentation as much as i can and do some pulls for anything i think might be relevant. For exmaple there is a whole bunch of awesome hidden zsh functions in axiom that I don't think are even mentioned. The nginx docker makes it really nice to look at screenshots or reports on the fly.

**Comment by 0xtavian** [comment]
@ResistanceIsUseless thanks for the kind words and detailed explanation. We are more than happy to merge a pull request if you have the time to add some type of permanent storage via Azure but at this time I dont think we will add cloud specific storage for any other provider, unless its a feature that many want. Every cloud provider has different storage options to choose from so it would take some time to go thru and figure out which one is best for that provider, and in the end, the user might not even want to use whatever storage solution we pick. I just dont see a way we can do this in a cloud agnostic way, so  we've left it up to the user to do what they want with the scan results after they are downloaded.

I do like the idea of pushing to Elasticsearch but IIRC you need kibana for a dashboard. Im down to explore options tho. Reach out to us on Discord if you want to share some ideas.

what do you mean "configs in profiles"?

Do you mean the provisioners, like full.json? https://github.com/pry0cc/axiom/tree/master/images/provisioners. If so you'd have to ask @pry0cc about these other build. it should be very possible to make your own build or use one of these

If you mean deployment profiles? https://github.com/pry0cc/axiom/tree/master/profiles these install tools we wanted the option to install after deploying the fleet, so they are optional.

or this config path? https://github.com/pry0cc/axiom/tree/master/configs which is used in full.json to set up cool things like zsh. Many of the configs in this folder are outdated however. We could honestly remove half and likely not notice a chance, they are just from older code.

**Comment by 0xtavian** [comment]
>  Is that something packer supports (making changes to a VM after deployed from an image) or something axiom does manually?

To my knowledge no. Packer will spin up a fresh VM to install the tools on. I dont believe using Packer to initialize a Packer made image is supported, or at least, its not used by axiom.

**Comment by ResistanceIsUseless** [comment]
Oh interesting. So the way axiom applies changes to VM's using the configs json is a custom thing not packer based like the image building. So the files are not interchangeable and are completely different. Good to know.

I tried to see if i could do a pull request on the wiki but it seems like its locked down. Am i doing something wrong or do you only allow specific people to edit that due to the nature of github? What if we created a new repo just for axiom documentation and imported that into this repo? Just a thought.

**Comment by 0xtavian** [comment]
@ResistanceIsUseless Yea thats a great idea. @pry0cc can you make another axiom-documentation repo?

**Comment by 0xtavian** [comment]
@ResistanceIsUseless we rewrote axiom-backup to asset with creating custom images https://github.com/pry0cc/axiom/pull/289 :)

**Comment by 0xtavian** [comment]
I would suggest looking into the Barebones JSON Packer build and using that as a template for custom Packer JSONS.
