### ISSUE TITLE
[Issue] Axiom-scan, nuclei -> parse error

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#309]
Hello guys,

This started to happen:

```

parse error: Invalid numeric literal at line 1, column 2
parse error: Invalid numeric literal at line 1, column 2
parse error: Invalid numeric literal at line 1, column 2
parse error: Invalid numeric literal at line 1, column 2
```
While doing ``axiom-scan urls.txt nuclei -t /home/op/nuclei-templates ``

After 20 minutes I realized I removed the ``-m`` flag. Maybe adding a condition to the parser to point the missing module flag? 

Thanks!

**Comment by 0xtavian** [comment]
hey @pdelteil two things about this. The first is that using nuclei with the `-t` option doesnt work with axiom (I think we should change this). We know this is how nuclei normally works without axiom but we've opted for a custom option `-w` so its more concise with other modules. Basically instead of providing the `-t` option you need to provide the `-w` (wordlist) option. Second is there is an ancillary benefit to not providing a module at all. Although undocumented, if no module is provided, the user supplied wordlist is simply split into equal parts per instance and uploaded to the appropriate instance. This can be very beneficial for more advanced users. I might make a split module and also error when `-m` is not present in the command. Thanks for bringing this up. I need to think about this a little more.

**Comment by pdelteil** [comment]
> hey @pdelteil two things about this. The first is that using nuclei with the `-t` option doesnt work with axiom (I think we should change this). We know this is how nuclei normally works without axiom but we've opted for a custom option `-w` so its more concise with other modules. Basically instead of providing the `-t` option you need to provide the `-w` (wordlist) option. Second is there is an ancillary benefit to not providing a module at all. Although undocumented, if no module is provided, the user supplied wordlist is simply split into equal parts per instance and uploaded to the appropriate instance. This can be very beneficial for more advanced users. I might make a split module and also error when `-m` is not present in the command. Thanks for bringing this up. I need to think about this a little more.

Hi there,

Actually the -t it does work. I was just testing it: 

``axiom-scan input.urls.txt -m nuclei -t /home/op/nuclei-templates/phalcon.yaml  -stats -si 180``

It did run only one template 

![Screenshot from 2021-05-02 23-06-40](https://user-images.githubusercontent.com/20244863/116838111-2ab94e80-ab9b-11eb-98f1-e8c7177d5f13.png)

And then if I remove the -t i got this:

![Screenshot from 2021-05-02 23-07-58](https://user-images.githubusercontent.com/20244863/116838127-445a9600-ab9b-11eb-9527-4c0677909042.png)


Can you show me how to use the -w (or -wL) flag?

**Comment by 0xtavian** [comment]
cool. thanks @pdelteil. you would use the -w flag the same way as -t, they seem to be interchangeable with the nuclei module. if you wanted to upload a local wordlist and use that for templates you would provide the -wL flag, however Im not sure if `-wL` works with directories. Im going to postpone adding an error message when a module isnt provided for now.

**Comment by pdelteil** [comment]
> cool. thanks @pdelteil. you would use the -w flag the same way as -t, they seem to be interchangeable with the nuclei module. if you wanted to upload a local wordlist and use that for templates you would provide the -wL flag, however Im not sure if `-wL` works with directories. Im going to postpone adding an error message when a module isnt provided for now.

Thanks for your answer. But instead of a wordlist it's easier just to use nuclei's config file (where you can define excluded/included tags, params and pretty much everything you might need to run a scan).

**Comment by Regala** [comment]
Hi! Can we reopen this issue? Was banging my head against the wall because I started getting the same error `parse error: Invalid numeric literal at line 1, column 2`. Axiom tries to start, but fails. So basically the argument `-m` should be checked if it exists or not (always I'm guessing?).

Cheers!
