### ISSUE TITLE
ssh problem

### ISSUE THREAD

**Issue by Krosskid12** [pry0cc/axiom#343]
![image](https://user-images.githubusercontent.com/73221787/118757021-e5c83400-b88b-11eb-9517-537fa67610a4.png)
Thanks in advance.

**Comment by 0xtavian** [comment]
@Krosskid12 are you authenticated to the CLI? What cloud provider are you using? if you cant resolve, running axiom-account-setup and axiom-rebuild should fix the issue.

**Comment by Krosskid12** [comment]
Hii i am using azure,i tried axiom-account-setup but didnt solve the problem.

**Comment by 0xtavian** [comment]
@0xtavian any luck? if you still have that setup, try to do `axiom-select` and reselect your fleet. It seems like you didnt get an IP from azure. do axiom-ls to validate you have inventory.

**Comment by froboot** [comment]
ola, estou com um problema para instalar o axiom: Your build failed :( Please take a look at the errors!
This can happen sometimes, if you have a [404] error while using Linode, this is likely because you need to request support for a larger image size to 18GB!
For support, take a screenshot of the last 20 lines and open a issue at https://github.com/pry0cc/axiom/issues
Sometimes just running a build again can work, so please try at least once: 'axiom-build', thanks!

Sua construção falhou :( Por favor, dê uma olhada nos erros!
Isso pode acontecer às vezes, se você tiver um erro [404] ao usar o Linode, é provável que seja necessário solicitar suporte para um tamanho de imagem maior para
 18 GB!
Para obter suporte, faça uma captura de tela das últimas 20 linhas e abra um problema em https://github.com/pry0cc/axiom/issues
Às vezes, apenas executar uma compilação novamente pode funcionar, então tente pelo menos uma vez: 'axiom-build', obrigado!

poderia mim ajudar ?

**Comment by 0xtavian** [comment]
@froboot Gostaria de criar uma nova caixa com a máquina em nuvem Ubuntu 20.04 no azure, instalar o axioma a partir destas instruções
https://github.com/pry0cc/axiom#installation---easy-install e tente novamente. Essa falha pode acontecer por vários motivos. Mostrar a saída completa do terminal ajudaria, mas ainda assim recomendaria excluir tudo e reinstalar em uma máquina nova. Se você ainda tiver erros, copie toda a saída do terminal e carregue-a aqui. Obrigado

**Comment by froboot** [comment]
obrigado!

**Comment by froboot** [comment]
olá, fiz varias coisas para instar o axiom: excluir todos os arquivo e
instalei de novo, excluir o droplet e instalei de novo , mas ontinua dando
o mesmo erro, enviarei a imagens do erro aqui. você poderia mim ajudar ?

**Comment by 0xtavian** [comment]
@Krosskid12 this as the OP hasnt responded and I have not been able to repeat. Feel free to reopen the issue or reach out to us on discord server run by 0x00sec, you'll find an axiom channel inside https://t.co/sd0q9YWINY
