### ISSUE TITLE
[Issue] Subfinder module scan result not merged

### ISSUE THREAD

**Issue by abdilahrf** [pry0cc/axiom#347]
The remote and local logs is saved correctly but the output is not merged 

This is the command that i run:
- axiom-fleet pwn -i=3 -t=2
- axiom-scan root.txt -m subfinder -o subs.txt

the output of scan is not saved in `subs.txt` is empty after the scan complete.

This screenshot below is explain the issue and showing the remote and local logs is correctly saved in place.

![image](https://user-images.githubusercontent.com/6015012/119249942-f992d380-bbc6-11eb-9b02-34b93a578580.png)

The error that maybe causing this is 

```
zsh:1: no matches found: pwn01:/home/op/scan/subfinder+1621749524/output/*
zsh:1: no matches found: pwn03:/home/op/scan/subfinder+1621749524/output/*
Generated 3 commands in total
Repeat set to 1
zsh:1: no matches found: pwn02:/home/op/scan/subfinder+1621749524/output/*
```

but i have no idea what was wrong here.

**Comment by 0xtavian** [comment]
@abdilahrf this is odd. also sorry for the late reply. I notice you are only scanning one target, if only scanning one target, only one axiom instance will have a job to do. the other will fail to exec the subfinder command and u will get the error during merge that no files are found because there was nothing on the remote isntances to pull from. However that doesnt explain why that last pwn01 didnt move the output it has to the user provided filename. Can you run axiom-update and try again? also try with multiple root targets as a target list, instead of just apel.com so we can test. Thanks

**Comment by abdilahrf** [comment]
Hi @0xtavian ,

I running the update already, but its still the same error
`axiom-scan root.txt -m subfinder -o subs.txt`

![image](https://user-images.githubusercontent.com/6015012/120427454-22238600-c39c-11eb-89b4-5b0d88efcef9.png)

now my root.txt file contains more than 10targets, but still the logs is saved locally and remotely but not the merged file 
`-o subs.txt` is not created the file `subs.txt` is still empty

**Comment by 0xtavian** [comment]
@abdilahrf can you provide the list of subs in root.txt?

**Comment by 0xtavian** [comment]
@abdilahrf closing as not able to repeat, feel free to open again if you have any more details
