### ISSUE TITLE
[feature] handling case when input items are fewer than number of instances

### ISSUE THREAD

**Issue by pdelteil** [pry0cc/axiom#448]
There's a border case when the amount of items in the input file are lower than the number of instances in a given fleet. 

For example, we want to run a scan using all nuclei templates on 20 urls having a fleet with 40 machines. 
This situation will output the following error  `cat: input: No such file or directory` because 20 instances are receiving empty input files. 

**Desired behavior** 

Warning about the number of item on the input file being lower than the amount of instances on a fleet. 
It would be useful for the user to know that (in this case) 20 instances are still available due to the small input.

**Comment by easyrider** [comment]
@0xtavian, what do you think about adjusting number of instances to host? 
I mean introducing `needed_instances` so the scan still works though not using fleet full capacity - works for me.
I'm using this solution and will create a PR if this is a desired functionality.

**Comment by 0xtavian** [comment]
Hey @easyrider, yea that’s not a bad idea. The way I originally thought I’d fix this issue is by creating a preflight check, which could be disabled by running `—no-preflight` or something. The idea was to ssh into each instance and use interlace to echo the hostname into a random path on the remote instance and then download the hostname from all instances and use that as selected.conf. This idea would auto fix itself if you had some down instances or instances not responding etc. basically try to dynamically  create a new selected.conf prior to the scan to ensure every instance is live. Somewhere during the preflight check I had planned to reduce total number of instances if it was greater than the total number of targets. Either way, your fix would provide a little more granular control over the size of the fleet. Go ahead and push a PR and we’ll see if we need to make some tweaks. Thanks!

**Comment by 0xtavian** [comment]
maybe we can name the option `—instances` or `—fleet-size` or something.

**Comment by easyrider** [comment]
@0xtavian, looks like my fix is much simpler and just fixes error when fleet is bigger than inputs - I hope the code is self explanatory.

Most naïve was to choose instances from the top to run jobs - I though about choosing random instances from the `selected.conf` list but this was it's easier to reason about what's being used at the moment.

My other 2 other biggest concerns about Axiom on Azure are:
1. interlace - a memory hog on Azure when instances > 5
2. `selected.conf` being not updated properly - showing deleted instances, etc

**Comment by 0xtavian** [comment]
@easyrider just to circle back to this: 
1. What are the specs on the vm? Try for at 2 vcpu / 2-4 gb ram for a cloud based controller.
2. selected.conf is updated via `axiom-select`. You should be able to exclude any instance you wish. It doesn’t automatically update when you delete instances.
Ping us on discord to troubleshoot further https://github.com/pry0cc/axiom/wiki

thanks for the PR!

**Comment by easyrider** [comment]
@0xtavian, no, problem - thanks for the great tool!

1. My spec is pretty poor: 1 vcpu, 1 GiB memory - I was thinking about optimizing it though as it is mostly CLI requests, I suppose `interlace` is the culprit here, have you considered other tools?
2. Yea, that's what I've observed - wouldn't that be helpful it those are removed automatically? I think it's pretty simple to do - not a big problem though
