### ISSUE TITLE
jq: error (at <stdin>:1361): Cannot iterate over null (null)

### ISSUE THREAD

**Issue by C90D** [pry0cc/axiom#449]
Error when generating fleet.
![image](https://user-images.githubusercontent.com/58028789/132937289-ae729e22-5a0f-42eb-8fb8-2e34e04f18fe.png)

**Comment by 0xtavian** [comment]
@C90D Yea i'm seeing this as well. Only on DO from what I can tell.

**Comment by C90D** [comment]
@0xtavian I rebuilt it many times, but it didn't work. What now

**Comment by 0xtavian** [comment]
@C90D well for one the boxes still get initialized. Run axiom-ls and you should see all the boxes that failed to list the IP in your screenshot. I think its happening because DO is slow to release IPs, maybe they are running low ATM. A quick fix is to add a 90 sec sleep here https://github.com/pry0cc/axiom/blob/master/interact/axiom-init#L225.

**Comment by C90D** [comment]
@0xtavian OK, thank you
