### ISSUE TITLE
[issue] axiom-connect/axiom-ssh gives me both connection timed out

### ISSUE THREAD

**Issue by Rz-Rz** [pry0cc/axiom#464]
Using Both axiom-connect or axiom-ssh gives me, after a few minutes, this error message: 
ssh: connect to host 178.XX.XXX.108 port 2266: Connection timed out

**Comment by 0xtavian** [comment]
@Rz-Rz  Run `axiom-ls` to see your instances. you can then do axiom-ssh [instance-name].

**Comment by coffeegist** [comment]
I think this can sometimes happen for unknown reasons, perhaps because axiom doesn't attempt to / properly configure firewall/vpc/routing to the instance? I'm running into the same thing, and after deploying the instance, I can see it with `axiom-ls`, but both `axiom-ssh <name>` and `axiom-connect` fail to connect with a timeout, although the instance is up and running.
