### ISSUE TITLE
modified my local zshrc config

### ISSUE THREAD

**Issue by iNoSec2** [pry0cc/axiom#485]
Axiom modified my local zshrc file... is it a normal behaviour?? because when i used it 1y ago it wasnt the case, it install the .zhrc on the digitalocean droplet not fuck my local install

**Comment by 0xtavian** [comment]
@iNoSec2 yea i can see how that can be annoying. I'll try to push a fix later this week.

**Comment by 0xtavian** [comment]
@iNoSec2  lmk if this fix works for you. Oh My Zsh should have automatically backed up before installing. You might have the backup in `$HOME/.zshrc.pre-oh-my-zsh`

**Comment by iNoSec2** [comment]
From some issues i saw here, you must put a warning in the readme stating this is an unstable project which can impact the main OS config files... it seems you cant handle all the different options you offer

**Comment by 0xtavian** [comment]
@iNoSec2 If you are referring to axiom-configure overwriting the .zshrc file, that only happens when installing Oh My Zsh. If you already have Oh My Zsh installed you can select zsh and it wont overwrite `.zshrc`, also selecting bash wont overwrite`.bashrc`. If selecting Bash or Zsh, we just append to the file and add `~/.axiom/interact` to path. I will update the help menu and docs with a warning that if selecting to install Oh My Zsh, that it will overwrite `.zshrc`. Note [the zsh config installed on the axiom controller](https://github.com/pry0cc/axiom/blob/master/configs/kali-zshrc), is not the one we install on [axiom-instances](https://github.com/pry0cc/axiom/blob/master/configs/zshrc).

In any case, no matter what option you pick for a shell, we are now backing up the original just in case. 


```
➜  ~ axiom-configure -h

 ▄▄▄      ▒██   ██▒ ██▓ ▒█████   ███▄ ▄███▓
▒████▄    ▒▒ █ █ ▒░▓██▒▒██▒  ██▒▓██▒▀█▀ ██▒
▒██  ▀█▄  ░░  █   ░▒██▒▒██░  ██▒▓██    ▓██░
░██▄▄▄▄██  ░ █ █ ▒ ░██░▒██   ██░▒██    ▒██
 ▓█   ▓██▒▒██▒ ▒██▒░██░░ ████▓▒░▒██▒   ░██▒
 ▒▒   ▓▒█░▒▒ ░ ░▓ ░░▓  ░ ▒░▒░▒░ ░ ▒░   ░  ░
  ▒   ▒▒ ░░░   ░▒ ░ ▒ ░  ░ ▒ ▒░ ░  ░      ░
  ░   ▒    ░    ░   ▒ ░░ ░ ░ ▒  ░      ░
      ░  ░ ░    ░   ░      ░ ░         ░

The Dynamic Infrastructure Framework for Everybody - @pry0cc & @0xtavian

We are lucky enough to be sponsored by the awesome SecurityTrails! 
Sign up for your free account here! https://securitytrails.com/app/account?utm_source=axiom

Description:
Examples:
  axiom-configure # kick off axiom configuration wizard
  axiom-configure --shell Zsh # Set default shell to Zsh via command line
  axiom-configure --config <axiom.json config data> # Use plaintext axiom.json data for account setup TODO: support axiom.json as a file
  axiom-configure --shell BASH --unattended --config <axiom.json config data>  # Use bash for default shell, do not promot, use plaintext axiom.json data for account setup
Usage:
  --config <axiom.json data>
    Setup account with data supplied from the command line (must be vaild data from axiom.json wrapped in single quotes)
  --unattended (optional)
    Avoid any promots, defaults to Oh My Zsh unless --shell argument is also provided
  --shell <Bash, Zsh, OMZ (Oh My Zsh)> (optional)
    Choose which shell to use
  --help
    Display this help menu
```
