### ISSUE TITLE
Nuclei Module Hanging

### ISSUE THREAD

**Issue by PR3R00T** [pry0cc/axiom#523]
Hello!

Im finding that on a fleet of 3 using the Axiom-scan -m nuclei module in a bash loop that after a random amount of loops the instance number starts to get buggy and then hangs and doesnt finish.

Module: [ nuclei ] | Extra Args: [  -json -t /home/op/custom/ -stats ] | Input: [ 8 targets ] | Scan uid: [ nuclei+1644510624 ]
Instances: 6 [ flyingdragon01 flyingdragon02 flyingdragon03 flyingdragon01 flyingdragon02 flyingdragon03 ]
Command: [ /home/op/go/bin/nuclei -silent -update-templates ; cat input | /home/op/go/bin/nuclei -o output -json -t /home/op/custom/ -stats ] | Ext: [txt]
Building file structure...[ OK ]
Uploading input files...
...
[INF] Templates added in last update: 3030
[INF] Templates loaded for scan: 1
{"duration":"0:00:00","errors":"0","hosts":"2","matched":"0","percent":"100","requests":"2","rps":"12","startedAt":"2022-02-10T16:30:30.286812896Z","templates":"1","total":"2"}
[INF] No results found. Better luck next time!
{"duration":"0:00:00","errors":"0","hosts":"2","matched":"0","percent":"100","requests":"2","rps":"7","startedAt":"2022-02-10T16:30:30.265811508Z","templates":"1","total":"2"}
[INF] No results found. Better luck next time!
{"duration":"0:00:01","errors":"0","hosts":"2","matched":"0","percent":"100","requests":"2","rps":"3","startedAt":"2022-02-10T16:30:30.333128049Z","templates":"1","total":"2"}
[INF] No results found. Better luck next time!

running latest version.

any ideas?

**Comment by 0xtavian** [comment]
@PR3R00T for nuclei when specifying a path to a template or directory of templates, use `-w` instead of `-t`. If supplying multiple paths to templates, the first path should be specified with `-w` and all subsequent paths should be specified with `-t`. I realize this isn’t native to nuclei’, but it’s required for axiom at the moment. I plan to make this more intuitive in the near
feature. We treat template paths as wordlist in axiom, to allow them to be switched out via command line and to support axiom’s `-wL` (wordlist local ) flag which allows uploading of a local template/wordlist to use with axiom-scan.
