### ISSUE TITLE
Integration  osmedeus

### ISSUE THREAD

**Issue by tequreq** [pry0cc/axiom#538]
i cant build osmedeus @0xtavian you can help me us.

**Comment by 0xtavian** [comment]
Hey @tequreq, 
If you want to build Osmedeus, I’d recommend building the image with osmedeus rather than axiom. Osmedeus also has their own discord server for support. 
Both Osmedeus and axiom use Packer so it might be possible with a few tweaks to build osmedeus with axiom. 
You could likely run axiom-fleet, axiom-init and axiom-rm but I’m not sure if you’d be able to run axiom-exec, axiom-ssh, axiom-scan etc. 
What exactly are you looking to accomplish with axiom and Osmedeus?

**Comment by tequreq** [comment]
thanks bro!

**Comment by pdelteil** [comment]
Hi @tequreq,

Please, give more context.

**Comment by j3ssie** [comment]
Hi all, it's j3ssie from Osmedeus here.
You can do the same horizontal scan with this command on Osmedeus like this.

```bash
# `-c 3` and `--chunk` flags
# means that the input file will be divided into 3 parts
# and spinning up 3 instances will be launched to scan each part separately
osmedeus cloud --chunk -c 3 -m vulnscan -t list-of-urls.txt
```
![Screen Shot 2022-12-17 at 15 40 44](https://user-images.githubusercontent.com/23289085/208233682-ab0ff712-9240-455b-9221-fcf6bdfef818.png)


After the scan was done it will sync back all the result to your local machine and delete the remote instance.
