### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by sp00kx** [pry0cc/axiom#573]
I have updated to latest build as of 20th July 2022. With a fleet of 15 instances on DigitalOcean after any axiom-scan module appears to complete, i am seeing this message pop up: /root/.axiom/interact/axiom-scan: line 1026: anew: command not found

Looking at that line of code in axiom-scan it appears to be associated with shutdown checking procedure, i am assuming when it is trying to poll the instances to see if the scan are finished. It seems to just keep cycling this error until i press Ctrl-C.

Anyone have any ideas?

**Comment by 0xtavian** [comment]
@sp00kx 
Make sure anew is in your path. You might need to restart your shell.

**Comment by mirhatx** [comment]
I'm still getting this error, I couldn't find a workaround for this problem.
Do you mind sharing how did you fix the problem? @sp00kx @0xtavian

**Comment by 0xtavian** [comment]
@mirhatx install anew (should be already installed) https://github.com/tomnomnom/anew and make sure it’s added to your path. If you run anew and get command not found, and it’s installed, it means it’s not in your path. What OS are you using? I think there is a bug with Mac installs atm that’s not correctly setting gopath or path.

**Comment by mrd17** [comment]
Hi @mirhatx ,

As @0xtavian said the error is because the anew is either not installed or not in the path.

For new members using Linux and facing this issue can follow these steps to fix this error.

1. Install anew using command 
 `go install -v github.com/tomnomnom/anew@latest`

3. If you get error installing using above command, then download binary from [here](https://github.com/tomnomnom/anew/releases)
4.  Then unzip file
     `tar -xvzf anew-<your_file_name>.tgz `

7.  ` cd anew`
8.  `sudo mv anew /usr/local/bin`

Now you should not receive this error.
