### ISSUE TITLE
axiom warning output using linode-cli 

### ISSUE THREAD

**Issue by bart3nder** [pry0cc/axiom#616]
Hi!
Thanks for amazing project, really useful.
So I get an error whenever axiom is interacting with linode-cli (axiom-fleet, axiom-ls, axiom-rm ...) saying:
```
Unable to determine if a new linode-cli package is available in pypi.  If this message persists, open a ticket or invoke with --suppress-warnings
```
It's still functioning correctly but it is some how slower due showing the error every single time. Is there anyway that I can fix it? I tried `pip3 uninstall linode-cli` and `pip3 install linode-cli` but no luck.
Thank you!

**Comment by pdelteil** [comment]
Maybe as a temporary solution you could create an alias: 

`linode-cli='linode-cli --suppress-warnings' `

**Comment by pdelteil** [comment]
> Maybe (as a temporary solution) you could create an **alias**:
> 
> `linode-cli='linode-cli --suppress-warnings' `

I'm not sure it would work.

**Comment by bart3nder** [comment]
Hmm,  didn't think that way. I just checked and unfortunately it didn't worked.
Thanks for your time Philippe!

**Comment by pdelteil** [comment]
I think the alias should be created on every instance, not on the local machine.

**Comment by pdelteil** [comment]
No problem. You want to get rid of the warning message, in order to do that without reinstalling `linode-cli` you could set up an alias linode-cli='linode-cli --suppress-warnings', that way every instance of your axiom fleet will run the command `linode-cli` but without the warnings, it's a trick. 

To do this you will need to add the alias to the `.bashrc` file of every instance. Something like this:

`axiom-exec 'echo "alias linode-cli=\"linode-cli --suppress-warnings\"" >> .bashrc' `   

I don't think is necessary but just in case run: 

`axiom-exec 'source /home/op/.bashrc'`

Now try running axiom again.

**Comment by bart3nder** [comment]
Ah, so it's like that, huh. I thought you meant I have to edit the axiom setup source to reach that. I understand that now. 
I did what you said but apparently there is no CLI tool for cloud providers (or at least for linode) on created instances, so the alias solution won't work since the only machine who is responsible to interact with the API is the local one and alias thing didn't fixed it (Still don't know why, I can not see any error or ...)
Thank you again for your time Philippe, I think I should go for deep uninstalling to fix the problem.

**Comment by pdelteil** [comment]
You are correct. I was wrong!

But still the same should work on your local machine. I'll try on my
instalation later.

**Comment by bart3nder** [comment]
Instead of `alias linode-cli='linode-cli --suppress-warnings'`, I edited `~/.axiom/providers/linode-functions.sh` directly and replaced every `linode-cli` with `linode-cli --suppress-warnings`. I can confirm it is fixed and works without any problem now.
Thank you!

**Comment by pdelteil** [comment]
Yes, that was the boring solution 😂 😂 😂 😂
