### ISSUE TITLE
Parallel issues

### ISSUE THREAD

**Issue by K4r1it0** [pry0cc/axiom#636]
Does the module runs on all instances in the same time. I am using puredns with https://wordlists-cdn.assetnote.io/data/manual/best-dns-wordlist.txt on 100 target + 100 digitalocean instances its been 15 hours and it doesn't finish. this wordlist takes around 20m in my personal digitalocean VPS. So when 100 instances runs at the same time i expect them to finish in 30m at least.

```
[{
    "command":"echo _target_ | /home/op/go/bin/puredns bruteforce _wordlist_ _target_ -r /home/op/lists/resolvers.txt  | tee _output_/_target_",
    "ext":"txt",
    "wordlist":"/home/op/best-dns-wordlist.txt",
    "threads":"1"
}]
```

**Comment by K4r1it0** [comment]
Update been 48+ hours

**Comment by pdelteil** [comment]
Hello there,

How are you running the scan?


Saludos,

*Philippe Delteil*

**Comment by K4r1it0** [comment]
axiom-scan hosts.txt -m pure.json -o dir
and it still not finished  
```
[{
    "command":"echo _target_ | /home/op/go/bin/puredns bruteforce _wordlist_ _target_ -r /home/op/lists/resolvers.txt  | tee _output_/_target_",
    "ext":"txt",
    "wordlist":"/home/op/best-dns-wordlist.txt",
    "threads":"1"
}]
```

**Comment by pdelteil** [comment]
Include the output of the first lines of execution. It should be puredns
without the json I don't know if that will make any difference. How many
selected instances do you have running?

**Comment by K4r1it0** [comment]
![axiom](https://user-images.githubusercontent.com/39193373/197426765-7ca14010-6d6f-4851-b981-71a350a6ae05.png)

**Comment by K4r1it0** [comment]
its been + 48 and the scan did not finish i am running puredns on 123 host on 100 instances using assetnote dns wordlist

**Comment by 0xtavian** [comment]
@K4r1it0 Sorry for the delay.

> I am running puredns on 123 host on 100 instances using assetnote dns wordlist. it seems like the scan running only on one host.
in this case, axiom will split the input file the best it can, 23 instances would be scanning 2 targets, 100 instances would be scanning 100 targets, for a total of 123 targets.

You can check each scanner by ssh-ing into the instance (axiom-ssh $name), cd to the unique scan working dir and check the input file and command. You can also attach to the tmux sessions running on the remote instances to see their progress ( or you can just `cat` the `stdout.log` and `stderr.log` files in the unique scan working dir. 

>Update: i tried axiom-exec "ps -aux | grep puredns" and only 10 hosts was executing puredns and i dont know why

Likely because the other scans completed. You can see which scans are still running by cd into the LOCAL tmp working dir `$HOME/.axiom/tmp/$module+$uid`, you can `ls output/` or you can `diff hosts status/completed/hosts`/.

Just to be sure, `/home/op/best-dns-wordlist.txt"` exists on the remote instances?
