### ISSUE TITLE
Add support for connecting multiple accounts

### ISSUE THREAD

**Issue by Nishantbhagat57** [pry0cc/axiom#664]
In my azure subscription I can only create 3 VMs per subscription. My subscription has a quota of 3 for resources of type PublicIpAddress as I have a student account.
But I have multiple Azure accounts available. Is there any feature so I can connect multiple azure account to axiom? @0xtavian
If not, can you give a solution so I can create more than 3 instances...

**Comment by 0xtavian** [comment]
@Nishantbhagat57 I would reach out to Azure and see if they will increase your limit. I just tested the solution [here](https://github.com/pry0cc/axiom/issues/302) and it still works.

**Comment by molitona** [comment]
@Nishantbhagat57 @0xtavian i can spawn only 3 instances with my azure free trial in same region, do you have same problem ?

**Comment by 0xtavian** [comment]
@molitona i think it’s three for the azure free trail. After a few billing cycles you can generally request an increase by opening up a support ticket.

**Comment by molitona** [comment]
@0xtavian It's 3 per region. But, I can start vms in other regions as well.
Does axiom support opening vms in multiple regions ?

**Comment by 0xtavian** [comment]
@molitona yea ofc. It’s in the help menu and wiki. Check out the help menu for `axiom-fleet —help`, and `axiom-init —help`. 
I believe `axiom-regions ls` might be supported for azure but lmk. 

However for azure axiom doesn’t transfer the image just because it is requested in that region. So if azure doesn’t automatically transfer the image to the new region than you’ll have to manually transfer the image via the az cli.

**Comment by molitona** [comment]
so i have 3 vms in region 1 

then i should type axiom-region select xxxx (other region) to get 3 other VMs with axiom-fleet ?

can you tell me where the image is located and what command to type with az cli to test it ?
