### ISSUE TITLE
modules/paramspider.json doesn't work with current version

### ISSUE THREAD

**Issue by colemanjp** [pry0cc/axiom#747]
It looks like paramspider just got a major refactor

```
usage: paramspider [-h] [-d DOMAIN] [-l LIST] [-s] [--proxy PROXY] [-p PLACEHOLDER]                            
   "ext":"",                                                                                                    │paramspider: error: Please provide either the -d option or the -l option.  
```
flags in module are no longer supported 
```
-  "command":"python3 -u /home/op/recon/ParamSpider/paramspider.py -d _target_ --exclude woff,css,js,png,svg,jpg -o _output_/_cleantarget_",
```

Related to #745

**Comment by 0xtavian** [comment]
Thanks @colemanjp! Its been fixed with https://github.com/pry0cc/axiom/commit/fc5ec53f90cd76af8273f1f02cdbaecf8fa2b46e and https://github.com/pry0cc/axiom/commit/1378e0e825cac9df8f2e562a1a2a7ea7ce2b6d50. Its now a Docker based module. You'll need to update (`axiom-update`), rebuild the [Default](https://github.com/pry0cc/axiom/blob/master/images/provisioners/default.json) provisioner (`axiom-build default`) and spin up a couple of fresh instances. 

Or you could install the updates on a fleet already spun up and avoid rebuilding (for now). You would still have to update the controller (`axiom-update`) or just copy the new [paramspider.json](https://github.com/pry0cc/axiom/blob/master/modules/paramspider.json) to `~/.axiom/modules/paramspider.json`
```
axiom-exec git clone https://github.com/0xtavian/minimal-pentesting-dockerfiles.git 
axiom-exec 'docker image build - < /home/op/minimal-pentesting-dockerfiles/paramspider/Dockerfile -t axiom/paramspider'
axiom-scan inputfile.txt -m paramspider
```

You can also LMK if you have any issues with the module. Thanks again.
