### ISSUE TITLE
What this script do?

### ISSUE THREAD

**Issue by shagustang** [pry0cc/axiom#767]
what does the python script: "ports.py" do?

![imagem_2023-10-24_190116470](https://github.com/pry0cc/axiom/assets/148913338/2d73167a-b386-4279-bb58-1a03ae1176b2)

**Comment by 0xtavian** [comment]
@shagustang doesnt do anything since it doesnt exist anymore. We replaced `ports.py` with [nmaptocsv](https://github.com/maaaaz/nmaptocsv), which can also be found [here](https://github.com/pry0cc/axiom/blob/master/interact/nmaptocsv.py). I updated the [wiki](https://github.com/pry0cc/axiom/wiki/Scans). 
The script takes an nmap.xml file and gets a list of IP:PORT combos to use with httpx and other tools

**Comment by shagustang** [comment]
Thanks for the answer. Using nmap would be like this: `axiom-scan ips.txt -m nmap -oX nmap.xml -T4 -p80,443,8080 -sV`?
